/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideoVideoIdRouteImport } from './routes/video/$videoId'
import { Route as NoteNoteIdRouteImport } from './routes/note/$noteId'

const SigninLazyRouteImport = createFileRoute('/signin')()
const WatchIndexLazyRouteImport = createFileRoute('/watch/')()
const ChatIndexLazyRouteImport = createFileRoute('/chat/')()
const WatchWatchIdLazyRouteImport = createFileRoute('/watch/$watchId')()
const ChatChatIdLazyRouteImport = createFileRoute('/chat/$chatId')()

const SigninLazyRoute = SigninLazyRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/signin.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchIndexLazyRoute = WatchIndexLazyRouteImport.update({
  id: '/watch/',
  path: '/watch/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/watch/index.lazy').then((d) => d.Route))
const ChatIndexLazyRoute = ChatIndexLazyRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/chat/index.lazy').then((d) => d.Route))
const WatchWatchIdLazyRoute = WatchWatchIdLazyRouteImport.update({
  id: '/watch/$watchId',
  path: '/watch/$watchId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/watch/$watchId.lazy').then((d) => d.Route),
)
const ChatChatIdLazyRoute = ChatChatIdLazyRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/chat/$chatId.lazy').then((d) => d.Route))
const VideoVideoIdRoute = VideoVideoIdRouteImport.update({
  id: '/video/$videoId',
  path: '/video/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteNoteIdRoute = NoteNoteIdRouteImport.update({
  id: '/note/$noteId',
  path: '/note/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninLazyRoute
  '/note/$noteId': typeof NoteNoteIdRoute
  '/video/$videoId': typeof VideoVideoIdRoute
  '/chat/$chatId': typeof ChatChatIdLazyRoute
  '/watch/$watchId': typeof WatchWatchIdLazyRoute
  '/chat/': typeof ChatIndexLazyRoute
  '/watch/': typeof WatchIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninLazyRoute
  '/note/$noteId': typeof NoteNoteIdRoute
  '/video/$videoId': typeof VideoVideoIdRoute
  '/chat/$chatId': typeof ChatChatIdLazyRoute
  '/watch/$watchId': typeof WatchWatchIdLazyRoute
  '/chat': typeof ChatIndexLazyRoute
  '/watch': typeof WatchIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/signin': typeof SigninLazyRoute
  '/note/$noteId': typeof NoteNoteIdRoute
  '/video/$videoId': typeof VideoVideoIdRoute
  '/chat/$chatId': typeof ChatChatIdLazyRoute
  '/watch/$watchId': typeof WatchWatchIdLazyRoute
  '/chat/': typeof ChatIndexLazyRoute
  '/watch/': typeof WatchIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/note/$noteId'
    | '/video/$videoId'
    | '/chat/$chatId'
    | '/watch/$watchId'
    | '/chat/'
    | '/watch/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/note/$noteId'
    | '/video/$videoId'
    | '/chat/$chatId'
    | '/watch/$watchId'
    | '/chat'
    | '/watch'
  id:
    | '__root__'
    | '/'
    | '/signin'
    | '/note/$noteId'
    | '/video/$videoId'
    | '/chat/$chatId'
    | '/watch/$watchId'
    | '/chat/'
    | '/watch/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SigninLazyRoute: typeof SigninLazyRoute
  NoteNoteIdRoute: typeof NoteNoteIdRoute
  VideoVideoIdRoute: typeof VideoVideoIdRoute
  ChatChatIdLazyRoute: typeof ChatChatIdLazyRoute
  WatchWatchIdLazyRoute: typeof WatchWatchIdLazyRoute
  ChatIndexLazyRoute: typeof ChatIndexLazyRoute
  WatchIndexLazyRoute: typeof WatchIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/': {
      id: '/watch/'
      path: '/watch'
      fullPath: '/watch/'
      preLoaderRoute: typeof WatchIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$watchId': {
      id: '/watch/$watchId'
      path: '/watch/$watchId'
      fullPath: '/watch/$watchId'
      preLoaderRoute: typeof WatchWatchIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$chatId': {
      id: '/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof ChatChatIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/$videoId': {
      id: '/video/$videoId'
      path: '/video/$videoId'
      fullPath: '/video/$videoId'
      preLoaderRoute: typeof VideoVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note/$noteId': {
      id: '/note/$noteId'
      path: '/note/$noteId'
      fullPath: '/note/$noteId'
      preLoaderRoute: typeof NoteNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SigninLazyRoute: SigninLazyRoute,
  NoteNoteIdRoute: NoteNoteIdRoute,
  VideoVideoIdRoute: VideoVideoIdRoute,
  ChatChatIdLazyRoute: ChatChatIdLazyRoute,
  WatchWatchIdLazyRoute: WatchWatchIdLazyRoute,
  ChatIndexLazyRoute: ChatIndexLazyRoute,
  WatchIndexLazyRoute: WatchIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
